# Midlight Realism Ultra Java Pack
# 高配真实感调色预设示例

screen.loading=18 26 40
text.code.0=93e8ff
text.code.1=d8f7ff
text.code.2=bafad4
text.code.3=ffe49d
text.code.4=ffb2a8
text.code.5=d4c3ff
text.code.6=ffbfd7
text.code.7=f2f7ff
fog.nether=0x2b1211
fog.end=0x0c0718
sky.end=0x1a1136